








/* INSERTS DE CATALOGO DE CHOC */
/* ===== Friis Holm ===== */
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ( 'Don Alfonso choc oscuro','negro','70','Pastelería','Barra','22 C°',4);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ( 'White Yuzu','blanco','40','Consumo','Barra','22 C°',4);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ( 'Medaglia Soy','negro','70','Pastelería','Barra','22 C°',4);

/* ===== Cacao Hunters ===== */
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Elizabeth','negro','71','Pastelería','Barra','22 C°',5);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Negro Tumaco','negro','82','Consumo','Barra','22 C°',5);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Tumaco Leche','con_leche','53','Pastelería','Barra','22 C°',5);

/* ===== St Moritz ===== */
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Flaquito','con_leche','40','Consumo','Barquilla','22 C°',6);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Chocolate Bitter','negro','70','Pastelería','Barra','22 C°',6);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('A la taza','negro','56','Consumo','Barra','22 C°',6);

/* ===== Milka ===== */
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Triple Caramelo','con_leche','30','Consumo','Barra','22 C°',7);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Oreo Blanco','blanco','30','Consumo','Barra','22 C°',7);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Strawberry Cheesecake','con_leche','40','Consumo','Barra','22 C°',7);

/* ===== The Hershey Company ===== */
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Cookies N Cream','blanco','Consumo','Barra','22 C°',CAMBIARPORNUMERO);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Kisses con leche','con_leche','30','Consumo','Gotas','22 C°',8);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Kit Kat Milk Chocolate','con_leche','70','Consumo','Barra','22 C°',8);

/* ===== Nibble Chocolate ===== */
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Coffee Dark Choc Brazil','negro','72','Consumo','Barra','22 C°',9);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Organic Dark Choc Peru','negro','72','Consumo','Barra','22 C°',9);
insert into CATAL_CHOCOLATES(NOMBRE, TIPO, CACAO_PORC, USO_RECOM, CLASIF_CHOC, TEMPERATURAS, ID_PRODUCTORA) values ('Organic Extr Dark Choc','negro','85','Consumo','Barra','22 C°',9);
commit;
/* FIN INSERTS DE CATALOGO DE CHOC */