insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Accra', 'fuerte', 'aporta sus características notas ácidas y afrutadas, sobre todo de frutos rojos', 030);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Criollo', 'suave', 'suave y semillas redondas, de color blanco a violeta, dulces y de sabor agradable. La mazorca se reconoce por tener diez surcos en pares bien marcados a lo largo.', 4016);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Criollo Andino', 'suave', 'son de color rojo o verde antes de llegar a la etapa de madurez, tienen una forma alargada con una punta inferior bien marcada; en la superficie cuenta con diez surcos profundos', 5115);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Trinitario', 'fuerte', 'resistente a enfermedades y tiene un sabor mucho más sutil, pueden apreciarse sabores a heno, roble miel, manzana y melón', 868);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Dominicano', 'fuerte', 'cáscara dura y lisa. Sus semillas son pequeñas aplanadas de sabor amargo, generalmente son moradas', 809);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Jamaica', 'suave', 'sabor suave y menos aromatico, a veces puede llegar a ser acido, con buen cuerpo para convertirse en chocolate', 1876);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Madra', 'suave', 'Hecho con las habas Criollo, aromáticas y ligeras, que se cultivan y cosechan en Java, color claro y cacao suave con refrescantes notas acidas', 17844);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Forastero amazonico', 'suave', 'alta resistencia a enfermedades y virus por lo que es muy codiciado para mejorar genéticamente otros tipos de cacao', 36502);
insert into CACAO(nombre_variedad, tipo, descripcion, id_lugar) values 
('Forastero', 'suave', 'Su sabor es fuerte, amargo, un poco ácido', 22215);