/* ===== INSERTS PRODUCTORA INICIO ==*/
insert into PRODUCTORA(nombre,logo,mision,tipo,id_lugar) values ('Acopagro',BFILENAME('direc_produc_logos', 'acopagro_logo.png'),'my mision increible','cacao',2);
insert into PRODUCTORA(nombre,logo,mision,tipo,id_lugar) values ('KKOReal',BFILENAME('direc_produc_logos', 'KKOReal_Logo.jpg'),'my mision test','cacao',1);
insert into PRODUCTORA(nombre,logo,mision,tipo,id_lugar) values ('Cofina',BFILENAME('direc_produc_logos', 'logo-cofinaOK2.png'),'my mision test','cacao',1);
commit;
/* ===== INSERTS PRODUCTORA FIN ==*/