/* ____===== INICIO DROPS =====____ */
/* ===== BORRAR TABLAS ===== */
drop table DISPONIBILIDAD_ENV;
drop table DET_EXPED;
drop table DET_PEDIDO;
drop table PRESENTACION;
drop table CATAL_CHOCOLATES;
drop table HIST_PRECIO;
drop table CACAO;
drop table PAGO;
drop table FACTURA;
drop table PEDIDO;
drop table CHOCOLATERIA;
drop table PRODUCTORA;
drop table CONTRATO;
drop table COND_PAGO_ENVIO;
drop table DET_FACTURA;
drop table FORMULA;
drop table FACT_BOMBONES;
drop table BOMBON_CATALOGO;
drop table PED_ACEPTADO;
drop table PED_RECHAZADO;
drop table LUGAR;
drop table PROD_CACAO;
drop table COND_CONT;
drop table COND_PED;
/* ===== BORRAR TABLAS FIN ===== */


/* ===== BORRAR NESTED TABLES ===== */
drop type DETALLE_NT;
drop type TEMPERATURA_NT;
drop type LOTE_NT;
drop type VOTO_NT;
drop type ENVIO_NT;
drop type HORARIO_NT;
/* ===== BORRAR NESTED TABLES FIN ===== */

/* ===== BORRAR ARRAYs ===== */
drop type CONTAC_ARRAY;
drop type INGRED_ARRAY;
/* ===== BORRAR ARRAYs FIN ===== */

/* ===== BORRAR TDAs ===== */
drop type DETALLE;
drop type CLASIFICACION;
drop type TEMP;
drop type LOTE;
drop type PRECIO;
drop type DIR;
drop type CONTAC;
drop type VOTO;
drop type ENVIO;
drop type TURNO;
/* ===== BORRAR TDAs FIN ===== */

/* ===== BORRAR DIRECTORIOS ===== */
drop directory direc_imagenes_productora;
/* ===== BORRAR DIRECTORIOS FIN ===== */

/* ____===== FIN DROPS =====____ */